repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: pytest-runner
        name: pytest
        language: system
        always_run: true
        entry: pytest # command
        pass_filenames: false